// Generated by CoffeeScript 1.6.3
(function() {
  var Liquid, generate_all, generate_index, github, repo;

  Liquid = require('liquid');

  generate_index = function(callback) {
    return $.get('../template/_layouts/default.html', function(data) {
      return callback(Liquid.Template.parse(data).render({
        site: {
          name: "123"
        }
      }));
    });
  };

  generate_all = function(callback) {
    return generate_index(function(index) {
      return callback({
        'index.html': index
      });
    });
  };

  generate_all(function(result) {
    return console.log(result);
  });

  github = new Github({
    username: "zh99998",
    password: "zh112998",
    auth: "basic"
  });

  repo = github.getRepo('zh99998', 'test');

  repo.getTree('master?recursive=true', function(err, tree) {
    return console.log(err, tree);
  });

}).call(this);
